name: "Run Python Checks"

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev,test]
      - name: Run linting
        run: |
          python -m flake8 -v --config .flake8 --black-config pyproject.toml --show-source
        continue-on-error: true
      - name: Run unit tests
        run: |
          python -m pytest -vvv --cov --cov-context=test --cov-report=xml
