name: "Run Python Checks"

on:
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          cache: pip
      - run: python3 --version
      - run: pip install --quiet --upgrade pip setuptools
      - run: pip install --editable '.[dev,test]'
      - run: ruff check -q --diff --output-format=full .
      - run: ruff format -q --diff --check .
        continue-on-error: true
      - run: pytest -vvv --cov --cov-context=test --cov-report=xml
